### ISSUE TITLE
numpy inconsistent requirements

### ISSUE THREAD

**Issue by sibirrer** [swagnercarena/paltas#49]
numpy is stated in the requirements that it should be >=1.13
but then it results in a raise when numpy is >1.24
This is inconsistent. How can this be resolved?
Thank you!

**Comment by swagnercarena** [comment]
Hi Simon,

It looks like this is an issue with numba wanting numpy to be version 1.24 or less. I imagine they'll patch this in a future version of numba, but for now I'll add a line to the requirements file.
