### ISSUE TITLE
outdated private function call in lenstronomy

### ISSUE THREAD

**Issue by sibirrer** [swagnercarena/paltas#55]
https://github.com/swagnercarena/paltas/blob/6f6e9ecdbb59cf10f59620ce07350f01037548b3/paltas/MainDeflector/simple_deflectors.py#L67

this should be changed and a call to lens_class() in the same lenstronomy file should be made

**Comment by swagnercarena** [comment]
It looks like this change isn't on the pip version of lenstronomy yet, so maybe we should hold back on this change for now?
